PROJECTS = [
    dict(slug="inventory-intelligence", title="Inventory Intelligence System", category="Inventory · AI Planning", summary="A live inventory platform replacing manual SAP stock checks with clear operational intelligence.", image="inventory.png", video="https://jaskirat-singh-portfolio.jaskiratsinghnarang.chatgpt.site/inventory-intelligence.mp4", result="₹28Cr+ inventory made visible in one live system."),
    dict(slug="employee-task-analyzer", title="Employee Task Update & Approval System", category="Workflow Automation · HR", summary="Scheduled task updates with automated Sub-HOD and HOD approvals, email routing, and a live management dashboard.", image="employee-task-system.jpg", result="Every update now has a timestamped, auditable approval trail."),
    dict(slug="lead-research-agent", title="Lead Research Agent", category="AI Research · Lead Generation", summary="A one-line prospect brief becomes a reviewed, verified lead list ready for Excel.", image=None, video="/static/video/lead-research-agent.mp4", result="Natural-language targeting becomes verified, export-ready lead intelligence."),
    dict(slug="invoice-process-agent", title="Invoice Process Agent", category="Document AI · Data Extraction", summary="Upload a document, request the fields you need, and export clean structured data.", image="invoice-process.png", result="Invoices become structured data without repetitive manual entry."),
    dict(slug="email-agent", title="Email Agent", category="AI Agent · Inbox Automation", summary="Inbox triage and reply drafting with human approval before anything sends.", image=None, result="Faster inbox handling while every outgoing message stays controlled."),
    dict(slug="event-lead-capture", title="Event Lead Capture System", category="CRM · Live Analytics", summary="A live exhibition dashboard capturing every contact with rep-by-rep visibility.", image=None, result="1,306 leads captured across six days with zero lost contacts."),
    dict(slug="aahar-lead-tracker", title="Aahar Lead Tracker", category="Team Operations · Lead CRM", summary="Messy exhibition data cleaned, distributed, and visible across nine sales teams.", image=None, result="Nine teams moved onto one live lead-ownership dashboard."),
]

WEBSITE_TEMPLATES = [
    dict(slug="murliwala-bakers", title="Murliwala Bakers", category="Bakery & local retail", image="murliwala-template-preview.jpg", video="/static/video/murliwala-template.mp4"),
    dict(slug="dubey-industries", title="Dubey Industries", category="Industrial & manufacturing", image="dubey-template-preview.jpg", video="/static/video/dubey-website-template.mp4"),
    dict(slug="the-detailing-gang", title="The Detailing Gang", category="Automotive & car detailing", image="car-detailing-template-preview.jpg", video="/static/video/car-detailing-template.mp4"),
]

SERVICES = [
    dict(slug="business-websites", number="01", title="Business Website Development", eyebrow="Presence & lead generation", summary="A focused, high-performance website designed to explain your value and turn visitors into enquiries.", timeline="1–3 weeks", deliverables=["Responsive custom design", "Lead forms and contact journeys", "Basic SEO and analytics", "Deployment and launch support"]),
    dict(slug="business-dashboards", number="02", title="Business Dashboards", eyebrow="Clarity & live reporting", summary="One reliable operational view that turns scattered business data into decisions.", timeline="2–4 weeks", deliverables=["KPI and performance dashboard", "Filters, charts and drill-downs", "Database or API integration", "Role-based access"]),
    dict(slug="workflow-automation", number="03", title="Workflow Automation", eyebrow="Less repetition, more control", summary="Reliable systems that replace repetitive handoffs, follow-ups and spreadsheet-heavy processes.", timeline="2–4 weeks", deliverables=["Current-process review", "Automated approvals and notifications", "Email, spreadsheet and API integrations", "Activity logs and documentation"]),
    dict(slug="ai-business-tools", number="04", title="AI Tools for Business", eyebrow="Applied AI, built responsibly", summary="Purpose-built AI assistants that research, process documents, prepare replies and support decisions.", timeline="3–6 weeks", deliverables=["Custom AI agent", "Business data integrations", "Human review workflows", "Testing and safeguards"]),
]

PROJECT_DETAILS = {
 "inventory-intelligence": ("Business applications development and AI integration", "Production system · 2025–26", "A complete inventory intelligence platform covering current stock, out-of-stock SKUs, non-moving items, ageing analysis, ABC–XYZ classification, item trace history and AI-powered monthly planning recommendations.", "The company needed a dedicated SAP user simply to check stock, while planners still assembled operational insight manually across disconnected reports and spreadsheets.", "I designed one focused decision surface that connects inventory data, exposes exceptions immediately and gives planners clear recommendations instead of another static report."),
 "employee-task-analyzer": ("Workflow design and Google Workspace automation", "Production system · 2025–26", "Employees submit structured task updates through secure individual forms. Each record follows the correct approval path from employee to Sub-HOD to HOD, while every decision is recorded in a live management dashboard.", "Daily work updates were fragmented and difficult to verify. Managers lacked a consistent record, while employees and approvers spent time chasing updates across departments.", "The system automates reminders, approval routing and email notifications while maintaining one live view of ownership, status and department performance."),
 "lead-research-agent": ("AI research workflow and full-stack development", "Production-ready system · 2026", "Users describe the companies they want, refine the brief with structured filters, review an AI-generated shortlist and approve the strongest fits. The agent then researches genuine company and contact details and exports a clean lead list.", "Manual prospecting consumed hours across search, qualification, verification and spreadsheet preparation before outreach could even begin.", "I built a human-in-the-loop workflow where AI proposes candidates, the user controls selection, and deeper verified research only runs on approved companies."),
 "invoice-process-agent": ("AI application development and document workflows", "Production system · 2026", "A document intelligence agent that reads PDFs, images, scanned bills and schema sheets, then extracts exactly what a user requests in plain English. Results remain conversational and export cleanly to Excel.", "Invoice teams were typing data manually across inconsistent formats, making extraction slow, repetitive and vulnerable to transcription errors.", "The tool combines document parsing with structured extraction so teams can compare invoices, summarize vendors, flag exceptions and produce consistent output from varied files."),
 "email-agent": ("AI agent development and messaging integration", "Production system · 2026", "The agent reads incoming mail, drafts an appropriate reply and requests approval through WhatsApp. Users can approve, edit, regenerate or skip, and compose new single or bulk emails.", "Routine inbox work was repetitive, but fully autonomous sending introduced unacceptable risk and removed human judgment from important communication.", "I automated triage and drafting while keeping an explicit, fast human approval checkpoint before every outgoing message."),
 "event-lead-capture": ("Full-stack development and real-time analytics", "Six-day live deployment · 2025", "A real-time lead capture and analytics platform deployed across 16 tablets at trade exhibitions, giving management a live breakdown of every representative’s activity.", "Fast-moving exhibitions made contact capture inconsistent, and management could not see team performance or recover missing context during the event.", "Standardized mobile capture, live synchronization and rep-level dashboards created one dependable record while the event was still happening."),
 "aahar-lead-tracker": ("CRM development and data operations", "Production system · 2025", "A focused operations platform that cleaned exhibition data, distributed leads across sales teams and gave management a live view of ownership, follow-up and progress.", "932 leads arrived in inconsistent formats without clear ownership or a reliable way to understand follow-up across nine teams.", "I standardized the source data, introduced transparent assignment rules and built a central dashboard that made every lead and owner accountable."),
}
for project in PROJECTS:
    project.update(dict(zip(("role", "status", "description", "challenge", "solution"), PROJECT_DETAILS[project["slug"]])))

SERVICE_DETAILS = {
 "business-websites": ("Go from an outdated or missing web presence to a credible, conversion-ready business website.", "Growing businesses, consultants and new ventures", ["Clarify your audience, offer and primary conversion goal.", "Design the page structure and visual direction around that goal.", "Build, test and launch a responsive website your team can confidently share."]),
 "business-dashboards": ("See the numbers that matter without waiting for manual reports or searching disconnected files.", "Operations, sales, inventory and management teams", ["Map the decisions your team makes and the data behind them.", "Create a clear information hierarchy and working prototype.", "Connect live data, validate the numbers and hand over the finished system."]),
 "workflow-automation": ("Give your team back time while keeping approvals, ownership and activity completely visible.", "Teams with recurring admin, approval or reporting work", ["Document the workflow and identify delays, duplication and risk.", "Design automation with the right checks and human approval points.", "Implement, test real scenarios and train the people who will use it."]),
 "ai-business-tools": ("Apply AI to a real business bottleneck with human oversight, useful data and measurable output.", "Teams exploring practical and secure uses of AI", ["Choose a valuable use case and define what good output means.", "Prototype against representative business data and edge cases.", "Build the workflow with safeguards, monitoring and a clear handover."]),
}
for service in SERVICES:
    service.update(dict(zip(("outcome", "best_for", "process"), SERVICE_DETAILS[service["slug"]])))
